channels = {
    "A/C Watts": (0, 3000, "A/C Watts$"),
    "AHU Watts": (0, 310, "AHU Watts$"),
    "Baseboard Heater 1 Watts": (0, 2000, "Baseboard.*Heater.*1.*Watts$"),
    "Baseboard Heater 2 Watts": (0, 2000, "Baseboard.*Heater.*2.*Watts$"),
    "Baseboard Heater 3 Watts": (0, 2000, "Baseboard.*Heater.*3.*Watts$"),
    "Bedroom Plugs Watts": (0, 3000, "Bedroom.?Plugs.*Watts$"),
    "Cold Water Avg C": (0.0001, 25, "Cold.*Water.*Avg.*C$"),
    "Cold Water Cubic Meter": (0, 25, "Cold.*Water.*Cubic.*Meter$"),
    "Dishwasher Watts": (0, 1200, "Dishwasher.*Watts$"),
    "Dryer (1) Watts": (0, 3500, "Dryer.*1.*Watts$"),
    "Dryer (2) Watts": (0, 3500, "Dryer.*2.*Watts$"),
    "Electrical Baseboard 1 Watts": (0, 2000, "Electrical.*Baseboard1.*Watts$"),
    "Electrical Baseboard 2 Watts": (0, 2000, "Electrical.*Baseboard2.*Watts$"),
    "Electrical Baseboard 3 Watts": (0, 2000, "Electrical.*Baseboard3.*Watts$"),
    "Electrical Baseboard 4 Watts": (0, 2000, "Electrical.*Baseboard4.*Watts$"),
    "Fridge Watts": (0, 627.2, "Fridge.*Watts$"),
    "Ground Level Plugs Watts": (0, 3000, "Ground.*Level.*Plugs?.*Watts$"),
    "HRV Watts": (0, 400, "HRV.*Watts$"),
    "Heat Recovery Water Avg C": (0, 35, "Heat.*Recovery.*Water.*Avg.*C$"),
    "Hot Water Avg C": (0.0001, 65, "Hot.*Water.*Avg.*C$"),
    "Hot Water Cubic Meter": (0, 25, "Hot.*Water.*Cubic.*Meter$"),
    "Hot Water Tank 1 Watts": (0, 4500, "Hot.*Water.*Tank.*1.*Watts$"),
    "Hot Water Tank 2 Watts": (0, 4500, "Hot.*Water.*Tank.*2.*Watts$"),
    "Kitchen Counter Plugs Watts": (0, 3000, "Kitchen.*Counter.*Plug?.*Watts$"),
    "Living Room Plugs Watts": (0, 3000, "Living.*Room.*Plugs?.*Watts$"),
    "Main Electricity 1 Watts": (0, 10000, "Main.*Electricity.*1.*Watts$"),
    "Main Electricity 2 Watts": (0, 10000, "Main.*Electricity.*2.*Watts$"),
    "Main Electricity Gen Watts": (-1500, 10000, "Main.*Electricity.*Gen.*Watts$"),
    "Main Electricity Gen Watts 1": (-1500, 10000, "Main.*Electricity.*Gen.*Watts.*1$"),
    "Main Floor Plugs Watts": (0, 3000, "Main.*Floor.*Plugs?.*Watts$"),
    "Natural Gas": (0, 25, "Natural.*Gas"),
    "Office Room Plugs Watts": (0, 3000, "Office.*Room.*Plugs?.*Watts$"),
    "PV Generation 1 Watts": (0, 1000, "PV.*Generation.*1.*Watts$"),
    "PV Generation 2 Watts": (0, 1000, "PV.*Generation.*2.*Watts$"),
    "Range (1) Watts": (0, 11300, "Range.*1.*Watts$"),
    "Range (2) Watts": (0, 11300, "Range.*2.*Watts$"),
    "Return Air Avg C": (0, 35, "Return.*Air.*Avg.*C$"),
    "Second Floor Plugs Watts": (0, 3000, "Second.*Floor.*Plugs?.*Watts$"),
    "Tankless WaterHeater Watts": (0, 250, "Tankless.*WaterHeater.*Watts$"),
    "Volts": (60, 180, "Volts"),
    "Washing Machine Watts": (0, 1000, "Washing.*Machine.*Watts$")
}