client_config_backend: settings
client_config:
  client_id: 302159697242-v309biregmfnvmfr3484q79k0j92pv44.apps.googleusercontent.com
  client_secret: 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
  
save_credentials: True
save_credentials_backend: file
save_credentials_file: ./credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install